/**
 * generate_history_js.js
 * Reads all Excel files in backfill_downloads/ and generates src/history.js
 * with historical member snapshot data embedded for use in the web app.
 */

import fs from 'fs';
import * as XLSX from 'xlsx';
import path from 'path';

const DOWNLOADS_DIR = './backfill_downloads/';
const OUTPUT_FILE = './src/history.js';

// history[memberId][snapshotDate] = { volL, volR, name }
const history = {};

const files = fs.readdirSync(DOWNLOADS_DIR)
  .filter(f => f.endsWith('.xlsx'))
  .sort();

console.log(`📂 Found ${files.length} Excel files`);

for (const file of files) {
  const match = file.match(/(\d{4}-\d{2})/);
  if (!match) continue;

  const datePart = match[1];
  const [year, month] = datePart.split('-');
  const lastDay = new Date(parseInt(year), parseInt(month), 0).getDate();
  const snapshotDate = `${datePart}-${String(lastDay).padStart(2, '0')}`;

  const filePath = path.join(DOWNLOADS_DIR, file);
  const buf = fs.readFileSync(filePath);
  const wb = XLSX.read(buf, { type: 'buffer' });
  const ws = wb.Sheets[wb.SheetNames[0]];
  const rows = XLSX.utils.sheet_to_json(ws, { header: 1 });

  let count = 0;
  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    if (!row || row.length < 18) continue;

    const memberRaw = String(row[1] || '');
    const parts = memberRaw.split('\n');
    const id = parts[0] ? parts[0].trim() : '';
    const name = parts.length > 1 ? parts[1].replace(/[()]/g, '').trim() : id;
    if (!id) continue;

    let volL = row[16];
    let volR = row[17];
    if (typeof volL === 'string') volL = parseFloat(volL.replace(/,/g, ''));
    if (typeof volR === 'string') volR = parseFloat(volR.replace(/,/g, ''));

    if (volL || volR) {
      if (!history[id]) history[id] = {};
      history[id][snapshotDate] = { volL: volL || 0, volR: volR || 0, name };
      count++;
    }
  }

  if (count > 0) {
    console.log(`  ✅ ${file} → ${snapshotDate}: ${count} members`);
  } else {
    console.log(`  ⚠️  ${file} → ${snapshotDate}: no data`);
  }
}

const memberCount = Object.keys(history).length;
const snapshotCount = Object.values(history).reduce((sum, m) => sum + Object.keys(m).length, 0);
console.log(`\n📊 Total: ${memberCount} unique members, ${snapshotCount} snapshots`);

const content = `// Auto-generated by generate_history_js.js — DO NOT EDIT MANUALLY
// Generated: ${new Date().toISOString()}
// ${memberCount} members, ${snapshotCount} snapshots (${Object.values(history).reduce((s, m) => { const dates = Object.keys(m); if (!dates.length) return s; const min = dates[0]; const max = dates[dates.length-1]; return `${min} → ${max}`; }, '')})

export const localHistory = ${JSON.stringify(history, null, 0)};
`;

fs.writeFileSync(OUTPUT_FILE, content);
console.log(`\n✅ Written to ${OUTPUT_FILE} (${(Buffer.byteLength(content)/1024).toFixed(1)} KB)`);
