[phases.setup]
nixPkgs = ["nodejs_20", "python39", "python39Packages.pip", "python39Packages.openpyxl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
