create table if not exists public.login_activity (
  id bigint generated by default as identity primary key,
  member_id text not null,
  member_name text not null,
  logged_at timestamptz not null default now(),
  ip text not null default 'unknown'
);

create index if not exists login_activity_logged_at_idx
  on public.login_activity (logged_at desc);
create index if not exists login_activity_member_logged_at_idx
  on public.login_activity (member_id, logged_at desc);

alter table public.login_activity enable row level security;
revoke all on public.login_activity from anon, authenticated;
